spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_URL}?useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  batch:
    jdbc:
      initialize-schema: always
  nome: "Nicholas"